[package]
name = "overload-strings"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]
license = "MIT/Apache-2.0"
description = "Haskell OverloadedStrings for Rust (using Into)"
repository = "https://github.com/birkenfeld/overload-strings"

[lib]
crate_type = ["dylib"]

[dependencies]
